---
- hosts: all 
  become: true
  task:
  vars:
    motd:
      - Ansible Managed Node by Sumaya, done on {{ Inventory_hostname }}
  vars_prompt:
      - name: username
        prompt: Input your username
        private: false
      - name: uid
        prompt: Input your own UID 
        private: false 

  tasks:

   - name: Banner MOTD
     ansible.builtin_debug:
       msg:
         - "{{ motd }}"

   - name: install python3 and pip3
     package:
       name:
         - python3
         - python3-pip
       state: latest
       update_cache: yes

   - name: install java open-jdk in Ubuntu
     apt:
         name: 
           - openjdk-17-jdk
         state: latest
         update_cache: yes
     when: ansible distribution == "Ubuntu"

   - name: Install java open-jdk in CentOS
     yum:
         name: 
           - java-11-openjdk
         state: latest
         update_cache: yes
     when: ansible distribution == "CentOS"

   - name: Create a user 
     ansible.builtin.user:
       name: "{{ username }}"
       comment: NewUser
       createhome: yes
       home: /home/"{{ username }}"
       shell: /bin/bash     
